Repository jupyter/notebook_shim, pull requests merged in 2022-09, with the labels that each got.

#12 raise ceiling on jupyter_server dependency to < 3
  notebook_shim/tests/test_extension.py
  pyproject.toml
  setup.cfg
Labels: enhancement

#14 switch to hatch build backend
  notebook_shim/_version.py
  pyproject.toml
  setup.cfg
  setup.py
Labels: maintenance

#15 remove dev version
  .github/workflows/test.yml
  notebook_shim/_version.py
  pyproject.toml
Labels: maintenance

#16 Automated Changelog Entry for 0.2.0 on main
  CHANGELOG.md
Labels: documentation

#17 Automated Changelog Entry for 0.2.0 on main
  CHANGELOG.md
Labels: documentation

#18 Bump version back to 0.1.0
  notebook_shim/_version.py
  pyproject.toml
Labels: maintenance
